title: "Github と CI を使った Grasshopper コンポーネント開発！！"
summary: "Grasshopperコンポーネントの開発を例にとって Github のいろんな機能を使った開発について紹介します。"
topics: ["github", "grasshopper", "csharp"]
published: true
price: 0 
chapters:
  - intro
  - build-with-github-actions
  - code-quality
  - code-maintenace
  - add-batch
  - add-github-pages
  - reference
